---
  debug: True
  outfile: "out.csv"
  p1_strategy: q-table
  p1_cost: 25
  p1_config:
    gamma: 0.8
    p: 0.7
    exploration_type: epsilon-greedy-visit-decay
    explore_config:
      epsilon: 0.5
      decay_lambda: 0.05
    estimate_type: td
    step_type: sample-average
  p0_strategy: periodic
  p0_config:
    avg_mv: 50
    delta: 50
  p0_cost: 1
  duration: 64000
  rew_type: constant_minus_cost_norm
  rew_config:
    c: 5
  obs_type: opp_LM

